services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: pzvhnbouqvwfcitclhmh
      POSTGRES_PASSWORD: wdkzulrqrwgfywqhbzro
      POSTGRES_DB: calendardb
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - webnet
    

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      DATABASE_URI: postgresql://pzvhnbouqvwfcitclhmh:wdkzulrqrwgfywqhbzro@db:5432/calendardb
    networks:
      - webnet

  frontend:
    build: ./frontend
    ports:
      - "5001:5001"
    volumes:
      - ./frontend:/app
    networks:
      - webnet
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/ssl/certs:ro
      - ./private:/etc/ssl/private:ro
      - ./frontend/public:/usr/share/nginx/html:ro 
    depends_on:
      - backend
      - frontend
    networks:
      - webnet

volumes:
  db_data:

networks:
  webnet:
