version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    depends_on:
      - db
    networks:
      - webnet

  frontend:
    build: ./frontend
    ports:
      - "5001:5000"
    volumes:
      - ./frontend:/app
    networks:
      - webnet

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: calendardb
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - webnet

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/ssl/certs:ro
      - ./private:/etc/ssl/private:ro
      - ./frontend/public:/usr/share/nginx/html:ro 
    depends_on:
      - backend
    networks:
      - webnet


volumes:
  db_data:

networks:
  webnet:
